name       : lrzip
version    : 0.631
release    : 1
source     :
    - https://github.com/ckolivas/lrzip/archive/v0.631.tar.gz : 10315c20d5a47590e7220c210735ba169677824d5672509266682eccec84d952
license    : GPL-2.0
component  : system.utils
summary    : lrzip - Long Range ZIP or LZMA RZIP
description: |
    A compression utility that excels at compressing large files (usually > 10-50 MB). Larger files and/or more free RAM means that the utility will be able to more effectively compress your files (ie: faster / smaller size), especially if the filesize(s) exceed 100 MB. You can either choose to optimise for speed (fast compression / decompression) or size, but not both.
builddeps  :
    - bzip2-devel
    - lzo-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
